name: Backend CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start services (Docker Compose)
        working-directory: infra
        run: docker compose up -d --build db redis backend

      - name: Install test deps inside backend (if not baked into image)
        working-directory: infra
        run: docker compose exec -T backend pip install -q pytest httpx pytest-timeout

      - name: Run tests
        working-directory: infra
        run: docker compose exec -T backend python -m pytest -q tests

      - name: Show backend logs on failure
        if: failure()
        working-directory: infra
        run: docker compose logs --no-log-prefix backend

      - name: Tear down
        if: always()
        working-directory: infra
        run: docker compose down -v
