
services:
  db:
    image: postgres:16
    container_name: sc_postgres
    environment:
      POSTGRES_USER: sc_user
      POSTGRES_PASSWORD: sc_pass
      POSTGRES_DB: sc_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sc_user -d sc_db"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7
    container_name: sc_redis
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4:8.10
    container_name: sc_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: sc_backend
    environment:
      # Usa la env para overridear el default de settings.py
      DATABASE_URL: postgresql+psycopg2://sc_user:sc_pass@db:5432/sc_db
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin123
    volumes:
      - ../backend:/app
      - backups_data:/app/backups
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pg_data:
  backups_data:
