"""proveedores compras stock_movs

Revision ID: 0aa5501f1477
Revises: 76e0ada34f51
Create Date: 2025-08-11 20:53:33.256148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa5501f1477'
down_revision: Union[str, Sequence[str], None] = '76e0ada34f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('cuit', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuit')
    )
    op.create_index(op.f('ix_proveedores_id'), 'proveedores', ['id'], unique=False)
    op.create_index(op.f('ix_proveedores_nombre'), 'proveedores', ['nombre'], unique=False)
    op.create_table('compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compras_id'), 'compras', ['id'], unique=False)
    op.create_index(op.f('ix_compras_proveedor_id'), 'compras', ['proveedor_id'], unique=False)
    op.create_table('stock_movimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('ref_tipo', sa.String(), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movimientos_id'), 'stock_movimientos', ['id'], unique=False)
    op.create_index(op.f('ix_stock_movimientos_producto_id'), 'stock_movimientos', ['producto_id'], unique=False)
    op.create_table('compra_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('costo_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['compras.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compra_items_compra_id'), 'compra_items', ['compra_id'], unique=False)
    op.create_index(op.f('ix_compra_items_id'), 'compra_items', ['id'], unique=False)
    op.create_index(op.f('ix_compra_items_producto_id'), 'compra_items', ['producto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compra_items_producto_id'), table_name='compra_items')
    op.drop_index(op.f('ix_compra_items_id'), table_name='compra_items')
    op.drop_index(op.f('ix_compra_items_compra_id'), table_name='compra_items')
    op.drop_table('compra_items')
    op.drop_index(op.f('ix_stock_movimientos_producto_id'), table_name='stock_movimientos')
    op.drop_index(op.f('ix_stock_movimientos_id'), table_name='stock_movimientos')
    op.drop_table('stock_movimientos')
    op.drop_index(op.f('ix_compras_proveedor_id'), table_name='compras')
    op.drop_index(op.f('ix_compras_id'), table_name='compras')
    op.drop_table('compras')
    op.drop_index(op.f('ix_proveedores_nombre'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_id'), table_name='proveedores')
    op.drop_table('proveedores')
    # ### end Alembic commands ###
