"""add_reportes_financieros_tables

Revision ID: 310587ef6e56
Revises: 9e5daa1a210c
Create Date: 2025-09-05 21:10:53.046200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '310587ef6e56'
down_revision: Union[str, Sequence[str], None] = '9e5daa1a210c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_precios_volumen_activo', table_name='precios_volumen')
    op.drop_index('ix_precios_volumen_cantidad_maxima', table_name='precios_volumen')
    op.drop_index('ix_precios_volumen_cantidad_minima', table_name='precios_volumen')
    op.drop_index('ix_precios_volumen_categoria_id', table_name='precios_volumen')
    op.drop_index('ix_precios_volumen_cliente_id', table_name='precios_volumen')
    op.drop_index('ix_precios_volumen_fecha_fin', table_name='precios_volumen')
    op.drop_index('ix_precios_volumen_fecha_inicio', table_name='precios_volumen')
    op.drop_index('ix_precios_volumen_id', table_name='precios_volumen')
    op.drop_index('ix_precios_volumen_prioridad', table_name='precios_volumen')
    op.drop_index('ix_precios_volumen_producto_id', table_name='precios_volumen')
    op.drop_table('precios_volumen')
    op.drop_index('ix_precio_historial_fecha_cambio', table_name='precio_historial')
    op.drop_index('ix_precio_historial_id', table_name='precio_historial')
    op.drop_index('ix_precio_historial_precio_id', table_name='precio_historial')
    op.drop_index('ix_precio_historial_producto_id', table_name='precio_historial')
    op.drop_index('ix_precio_historial_tipo_cambio', table_name='precio_historial')
    op.drop_table('precio_historial')
    op.drop_index('ix_precios_categoria_activo', table_name='precios_categoria')
    op.drop_index('ix_precios_categoria_categoria_id', table_name='precios_categoria')
    op.drop_index('ix_precios_categoria_cliente_id', table_name='precios_categoria')
    op.drop_index('ix_precios_categoria_fecha_fin', table_name='precios_categoria')
    op.drop_index('ix_precios_categoria_fecha_inicio', table_name='precios_categoria')
    op.drop_index('ix_precios_categoria_id', table_name='precios_categoria')
    op.drop_index('ix_precios_categoria_prioridad', table_name='precios_categoria')
    op.drop_index('ix_precios_categoria_producto_id', table_name='precios_categoria')
    op.drop_table('precios_categoria')
    op.drop_index('ix_alertas_inventario_estado', table_name='alertas_inventario')
    op.drop_index('ix_alertas_inventario_prioridad', table_name='alertas_inventario')
    op.drop_index('ix_alertas_inventario_producto_id', table_name='alertas_inventario')
    op.drop_index('ix_alertas_inventario_tipo', table_name='alertas_inventario')
    op.drop_table('alertas_inventario')
    op.drop_index('ix_precios_aplicados_cliente_id', table_name='precios_aplicados')
    op.drop_index('ix_precios_aplicados_fecha_aplicacion', table_name='precios_aplicados')
    op.drop_index('ix_precios_aplicados_id', table_name='precios_aplicados')
    op.drop_index('ix_precios_aplicados_precio_id', table_name='precios_aplicados')
    op.drop_index('ix_precios_aplicados_producto_id', table_name='precios_aplicados')
    op.drop_index('ix_precios_aplicados_tipo_precio', table_name='precios_aplicados')
    op.drop_index('ix_precios_aplicados_venta_id', table_name='precios_aplicados')
    op.drop_table('precios_aplicados')
    op.drop_index('ix_configuracion_inventario_activo', table_name='configuracion_inventario')
    op.drop_index('ix_configuracion_inventario_producto_id', table_name='configuracion_inventario')
    op.drop_table('configuracion_inventario')
    op.drop_index('ix_precios_producto_activo', table_name='precios_producto')
    op.drop_index('ix_precios_producto_categoria_id', table_name='precios_producto')
    op.drop_index('ix_precios_producto_cliente_id', table_name='precios_producto')
    op.drop_index('ix_precios_producto_estado', table_name='precios_producto')
    op.drop_index('ix_precios_producto_fecha_fin', table_name='precios_producto')
    op.drop_index('ix_precios_producto_fecha_inicio', table_name='precios_producto')
    op.drop_index('ix_precios_producto_id', table_name='precios_producto')
    op.drop_index('ix_precios_producto_prioridad', table_name='precios_producto')
    op.drop_index('ix_precios_producto_producto_id', table_name='precios_producto')
    op.drop_index('ix_precios_producto_tipo', table_name='precios_producto')
    op.drop_table('precios_producto')
    op.drop_table('auditoria')
    op.drop_index('ix_reorden_automatico_estado', table_name='reorden_automatico')
    op.drop_index('ix_reorden_automatico_producto_id', table_name='reorden_automatico')
    op.drop_index('ix_reorden_automatico_proveedor_id', table_name='reorden_automatico')
    op.drop_table('reorden_automatico')
    op.drop_index('ix_movimientos_inventario_fecha_movimiento', table_name='movimientos_inventario')
    op.drop_index('ix_movimientos_inventario_producto_id', table_name='movimientos_inventario')
    op.drop_index('ix_movimientos_inventario_tipo_movimiento', table_name='movimientos_inventario')
    op.drop_table('movimientos_inventario')
    op.drop_index('ix_precios_estacionales_activo', table_name='precios_estacionales')
    op.drop_index('ix_precios_estacionales_categoria_id', table_name='precios_estacionales')
    op.drop_index('ix_precios_estacionales_cliente_id', table_name='precios_estacionales')
    op.drop_index('ix_precios_estacionales_fecha_fin', table_name='precios_estacionales')
    op.drop_index('ix_precios_estacionales_fecha_inicio', table_name='precios_estacionales')
    op.drop_index('ix_precios_estacionales_id', table_name='precios_estacionales')
    op.drop_index('ix_precios_estacionales_nombre_temporada', table_name='precios_estacionales')
    op.drop_index('ix_precios_estacionales_prioridad', table_name='precios_estacionales')
    op.drop_index('ix_precios_estacionales_producto_id', table_name='precios_estacionales')
    op.drop_table('precios_estacionales')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('precios_estacionales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre_temporada', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descuento_porcentaje', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('descuento_monto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('precio_especial', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('categoria_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_inicio', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('fecha_fin', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('creado_por', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('prioridad', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='precios_estacionales_pkey')
    )
    op.create_index('ix_precios_estacionales_producto_id', 'precios_estacionales', ['producto_id'], unique=False)
    op.create_index('ix_precios_estacionales_prioridad', 'precios_estacionales', ['prioridad'], unique=False)
    op.create_index('ix_precios_estacionales_nombre_temporada', 'precios_estacionales', ['nombre_temporada'], unique=False)
    op.create_index('ix_precios_estacionales_id', 'precios_estacionales', ['id'], unique=False)
    op.create_index('ix_precios_estacionales_fecha_inicio', 'precios_estacionales', ['fecha_inicio'], unique=False)
    op.create_index('ix_precios_estacionales_fecha_fin', 'precios_estacionales', ['fecha_fin'], unique=False)
    op.create_index('ix_precios_estacionales_cliente_id', 'precios_estacionales', ['cliente_id'], unique=False)
    op.create_index('ix_precios_estacionales_categoria_id', 'precios_estacionales', ['categoria_id'], unique=False)
    op.create_index('ix_precios_estacionales_activo', 'precios_estacionales', ['activo'], unique=False)
    op.create_table('movimientos_inventario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_movimiento', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('cantidad_anterior', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('cantidad_nueva', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('referencia_tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('referencia_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_movimiento', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('motivo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('costo_unitario', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('costo_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name='movimientos_inventario_producto_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], name='movimientos_inventario_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='movimientos_inventario_pkey')
    )
    op.create_index('ix_movimientos_inventario_tipo_movimiento', 'movimientos_inventario', ['tipo_movimiento'], unique=False)
    op.create_index('ix_movimientos_inventario_producto_id', 'movimientos_inventario', ['producto_id'], unique=False)
    op.create_index('ix_movimientos_inventario_fecha_movimiento', 'movimientos_inventario', ['fecha_movimiento'], unique=False)
    op.create_table('reorden_automatico',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proveedor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cantidad_sugerida', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('costo_estimado', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fecha_sugerida', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'pendiente'::character varying"), autoincrement=False, nullable=True),
    sa.Column('aprobado_por', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_aprobacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('notas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['aprobado_por'], ['users.id'], name='reorden_automatico_aprobado_por_fkey'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name='reorden_automatico_producto_id_fkey'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], name='reorden_automatico_proveedor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reorden_automatico_pkey')
    )
    op.create_index('ix_reorden_automatico_proveedor_id', 'reorden_automatico', ['proveedor_id'], unique=False)
    op.create_index('ix_reorden_automatico_producto_id', 'reorden_automatico', ['producto_id'], unique=False)
    op.create_index('ix_reorden_automatico_estado', 'reorden_automatico', ['estado'], unique=False)
    op.create_table('auditoria',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('actor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('accion', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='auditoria_pkey')
    )
    op.create_table('precios_producto',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', postgresql.ENUM('base', 'cliente', 'volumen', 'categoria', 'estacional', 'promocional', name='tipoprecio'), autoincrement=False, nullable=False),
    sa.Column('estado', postgresql.ENUM('activo', 'inactivo', 'expirado', 'suspendido', name='estadoprecio'), server_default=sa.text("'activo'::estadoprecio"), autoincrement=False, nullable=True),
    sa.Column('precio_base', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('precio_especial', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('descuento_porcentaje', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('descuento_monto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('categoria_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cantidad_minima', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cantidad_maxima', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fecha_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('fecha_fin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('creado_por', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('fecha_actualizacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('prioridad', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='precios_producto_pkey')
    )
    op.create_index('ix_precios_producto_tipo', 'precios_producto', ['tipo'], unique=False)
    op.create_index('ix_precios_producto_producto_id', 'precios_producto', ['producto_id'], unique=False)
    op.create_index('ix_precios_producto_prioridad', 'precios_producto', ['prioridad'], unique=False)
    op.create_index('ix_precios_producto_id', 'precios_producto', ['id'], unique=False)
    op.create_index('ix_precios_producto_fecha_inicio', 'precios_producto', ['fecha_inicio'], unique=False)
    op.create_index('ix_precios_producto_fecha_fin', 'precios_producto', ['fecha_fin'], unique=False)
    op.create_index('ix_precios_producto_estado', 'precios_producto', ['estado'], unique=False)
    op.create_index('ix_precios_producto_cliente_id', 'precios_producto', ['cliente_id'], unique=False)
    op.create_index('ix_precios_producto_categoria_id', 'precios_producto', ['categoria_id'], unique=False)
    op.create_index('ix_precios_producto_activo', 'precios_producto', ['activo'], unique=False)
    op.create_table('configuracion_inventario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stock_minimo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('stock_maximo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('punto_reorden', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cantidad_reorden', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('alerta_stock_bajo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('alerta_stock_critico', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('alerta_vencimiento', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('dias_vencimiento_alerta', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=True),
    sa.Column('alerta_movimiento_grande', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('umbral_movimiento_grande', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('fecha_actualizacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name='configuracion_inventario_producto_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='configuracion_inventario_pkey'),
    sa.UniqueConstraint('producto_id', name='configuracion_inventario_producto_id_key')
    )
    op.create_index('ix_configuracion_inventario_producto_id', 'configuracion_inventario', ['producto_id'], unique=False)
    op.create_index('ix_configuracion_inventario_activo', 'configuracion_inventario', ['activo'], unique=False)
    op.create_table('precios_aplicados',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('venta_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('precio_base', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('precio_final', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('descuento_aplicado', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('porcentaje_descuento', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tipo_precio', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('precio_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('precio_tabla', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cantidad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fecha_aplicacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='precios_aplicados_pkey')
    )
    op.create_index('ix_precios_aplicados_venta_id', 'precios_aplicados', ['venta_id'], unique=False)
    op.create_index('ix_precios_aplicados_tipo_precio', 'precios_aplicados', ['tipo_precio'], unique=False)
    op.create_index('ix_precios_aplicados_producto_id', 'precios_aplicados', ['producto_id'], unique=False)
    op.create_index('ix_precios_aplicados_precio_id', 'precios_aplicados', ['precio_id'], unique=False)
    op.create_index('ix_precios_aplicados_id', 'precios_aplicados', ['id'], unique=False)
    op.create_index('ix_precios_aplicados_fecha_aplicacion', 'precios_aplicados', ['fecha_aplicacion'], unique=False)
    op.create_index('ix_precios_aplicados_cliente_id', 'precios_aplicados', ['cliente_id'], unique=False)
    op.create_table('alertas_inventario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'pendiente'::character varying"), autoincrement=False, nullable=True),
    sa.Column('titulo', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('mensaje', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('prioridad', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('stock_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('stock_minimo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('stock_critico', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dias_vencimiento', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('fecha_resolucion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('resuelta_por', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notas_resolucion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name='alertas_inventario_producto_id_fkey'),
    sa.ForeignKeyConstraint(['resuelta_por'], ['users.id'], name='alertas_inventario_resuelta_por_fkey'),
    sa.PrimaryKeyConstraint('id', name='alertas_inventario_pkey')
    )
    op.create_index('ix_alertas_inventario_tipo', 'alertas_inventario', ['tipo'], unique=False)
    op.create_index('ix_alertas_inventario_producto_id', 'alertas_inventario', ['producto_id'], unique=False)
    op.create_index('ix_alertas_inventario_prioridad', 'alertas_inventario', ['prioridad'], unique=False)
    op.create_index('ix_alertas_inventario_estado', 'alertas_inventario', ['estado'], unique=False)
    op.create_table('precios_categoria',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('categoria_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descuento_porcentaje', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('descuento_monto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('multiplicador', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('fecha_fin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('creado_por', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('prioridad', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='precios_categoria_pkey')
    )
    op.create_index('ix_precios_categoria_producto_id', 'precios_categoria', ['producto_id'], unique=False)
    op.create_index('ix_precios_categoria_prioridad', 'precios_categoria', ['prioridad'], unique=False)
    op.create_index('ix_precios_categoria_id', 'precios_categoria', ['id'], unique=False)
    op.create_index('ix_precios_categoria_fecha_inicio', 'precios_categoria', ['fecha_inicio'], unique=False)
    op.create_index('ix_precios_categoria_fecha_fin', 'precios_categoria', ['fecha_fin'], unique=False)
    op.create_index('ix_precios_categoria_cliente_id', 'precios_categoria', ['cliente_id'], unique=False)
    op.create_index('ix_precios_categoria_categoria_id', 'precios_categoria', ['categoria_id'], unique=False)
    op.create_index('ix_precios_categoria_activo', 'precios_categoria', ['activo'], unique=False)
    op.create_table('precio_historial',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_cambio', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('precio_anterior', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('precio_nuevo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('descuento_anterior', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('descuento_nuevo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('precio_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('precio_tabla', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('motivo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_cambio', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='precio_historial_pkey')
    )
    op.create_index('ix_precio_historial_tipo_cambio', 'precio_historial', ['tipo_cambio'], unique=False)
    op.create_index('ix_precio_historial_producto_id', 'precio_historial', ['producto_id'], unique=False)
    op.create_index('ix_precio_historial_precio_id', 'precio_historial', ['precio_id'], unique=False)
    op.create_index('ix_precio_historial_id', 'precio_historial', ['id'], unique=False)
    op.create_index('ix_precio_historial_fecha_cambio', 'precio_historial', ['fecha_cambio'], unique=False)
    op.create_table('precios_volumen',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad_minima', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('cantidad_maxima', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('descuento_porcentaje', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('descuento_monto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('precio_especial', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('categoria_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('fecha_fin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('creado_por', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('prioridad', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='precios_volumen_pkey')
    )
    op.create_index('ix_precios_volumen_producto_id', 'precios_volumen', ['producto_id'], unique=False)
    op.create_index('ix_precios_volumen_prioridad', 'precios_volumen', ['prioridad'], unique=False)
    op.create_index('ix_precios_volumen_id', 'precios_volumen', ['id'], unique=False)
    op.create_index('ix_precios_volumen_fecha_inicio', 'precios_volumen', ['fecha_inicio'], unique=False)
    op.create_index('ix_precios_volumen_fecha_fin', 'precios_volumen', ['fecha_fin'], unique=False)
    op.create_index('ix_precios_volumen_cliente_id', 'precios_volumen', ['cliente_id'], unique=False)
    op.create_index('ix_precios_volumen_categoria_id', 'precios_volumen', ['categoria_id'], unique=False)
    op.create_index('ix_precios_volumen_cantidad_minima', 'precios_volumen', ['cantidad_minima'], unique=False)
    op.create_index('ix_precios_volumen_cantidad_maxima', 'precios_volumen', ['cantidad_maxima'], unique=False)
    op.create_index('ix_precios_volumen_activo', 'precios_volumen', ['activo'], unique=False)
    # ### end Alembic commands ###
