"""add_inventario_tables

Revision ID: 31dd9753feba
Revises: e8e18a9dcd38
Create Date: 2025-09-05 19:08:16.963677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31dd9753feba'
down_revision: Union[str, Sequence[str], None] = 'e8e18a9dcd38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('descuento_usos')
    op.drop_index('ix_notificaciones_es_urgente', table_name='notificaciones')
    op.drop_index('ix_notificaciones_estado', table_name='notificaciones')
    op.drop_index('ix_notificaciones_fecha_creacion', table_name='notificaciones')
    op.drop_index('ix_notificaciones_tipo', table_name='notificaciones')
    op.drop_index('ix_notificaciones_titulo', table_name='notificaciones')
    op.drop_index('ix_notificaciones_usuario_id', table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index('ix_descuentos_codigo', table_name='descuentos')
    op.drop_index('ix_descuentos_es_activo', table_name='descuentos')
    op.drop_index('ix_descuentos_estado', table_name='descuentos')
    op.drop_index('ix_descuentos_tipo', table_name='descuentos')
    op.drop_table('descuentos')
    op.drop_table('notificaciones_usuarios')
    op.drop_table('auditoria')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('actor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('accion', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='auditoria_pkey')
    )
    op.create_table('notificaciones_usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('notificacion_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estado', postgresql.ENUM('pendiente', 'enviada', 'leida', 'archivada', name='estadonotificacion'), server_default=sa.text("'pendiente'::estadonotificacion"), autoincrement=False, nullable=False),
    sa.Column('fecha_lectura', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='notificaciones_usuarios_pkey')
    )
    op.create_table('descuentos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tipo', postgresql.ENUM('porcentaje', 'monto_fijo', 'descuento_volumen', 'descuento_cliente', 'promocion_temporal', name='tipodescuento'), autoincrement=False, nullable=False),
    sa.Column('valor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('valor_minimo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('valor_maximo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('limite_usos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usos_por_cliente', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usos_actuales', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('fecha_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('fecha_fin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('estado', postgresql.ENUM('activo', 'inactivo', 'expirado', 'agotado', name='estadodescuento'), server_default=sa.text("'activo'::estadodescuento"), autoincrement=False, nullable=False),
    sa.Column('es_activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('aplica_envio', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('aplica_impuestos', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('productos_ids', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('clientes_ids', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('categorias_ids', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('creado_por', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notas_internas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['users.id'], name='descuentos_creado_por_fkey'),
    sa.PrimaryKeyConstraint('id', name='descuentos_pkey'),
    sa.UniqueConstraint('codigo', name='descuentos_codigo_key')
    )
    op.create_index('ix_descuentos_tipo', 'descuentos', ['tipo'], unique=False)
    op.create_index('ix_descuentos_estado', 'descuentos', ['estado'], unique=False)
    op.create_index('ix_descuentos_es_activo', 'descuentos', ['es_activo'], unique=False)
    op.create_index('ix_descuentos_codigo', 'descuentos', ['codigo'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('mensaje', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tipo', postgresql.ENUM('stock_bajo', 'venta_importante', 'sistema', 'mantenimiento', 'error', 'info', 'warning', name='tiponotificacion'), autoincrement=False, nullable=False),
    sa.Column('estado', postgresql.ENUM('pendiente', 'enviada', 'leida', 'archivada', name='estadonotificacion'), server_default=sa.text("'pendiente'::estadonotificacion"), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('entidad_tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('entidad_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('fecha_envio', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_lectura', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('es_urgente', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('requiere_accion', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('datos_adicionales', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='notificaciones_pkey')
    )
    op.create_index('ix_notificaciones_usuario_id', 'notificaciones', ['usuario_id'], unique=False)
    op.create_index('ix_notificaciones_titulo', 'notificaciones', ['titulo'], unique=False)
    op.create_index('ix_notificaciones_tipo', 'notificaciones', ['tipo'], unique=False)
    op.create_index('ix_notificaciones_fecha_creacion', 'notificaciones', ['fecha_creacion'], unique=False)
    op.create_index('ix_notificaciones_estado', 'notificaciones', ['estado'], unique=False)
    op.create_index('ix_notificaciones_es_urgente', 'notificaciones', ['es_urgente'], unique=False)
    op.create_table('descuento_usos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descuento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('venta_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('monto_original', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('monto_descuento', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('monto_final', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fecha_uso', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('ip_cliente', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='descuento_usos_pkey')
    )
    # ### end Alembic commands ###
