"""venta items out stock

Revision ID: 5cb3f141eb55
Revises: 0aa5501f1477
Create Date: 2025-08-11 21:56:05.867978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cb3f141eb55'
down_revision: Union[str, Sequence[str], None] = '0aa5501f1477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ventas', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ventas', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_ventas_cliente_id'), 'ventas', ['cliente_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ventas_cliente_id'), table_name='ventas')
    op.alter_column('ventas', 'fecha',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('ventas', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
