"""add_notificaciones_tables

Revision ID: c544a0180d0b
Revises: 1f27ffa8f60f
Create Date: 2025-09-05 18:23:31.138366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c544a0180d0b'
down_revision: Union[str, Sequence[str], None] = '1f27ffa8f60f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('table_name', sa.String(length=120), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', name='auditaction'), nullable=False),
    sa.Column('record_id', sa.String(length=120), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_created_at', 'audit_logs', [sa.text('created_at DESC')], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index('ix_audit_tbl_rec_time', 'audit_logs', ['table_name', 'record_id', sa.text('created_at DESC')], unique=False)
    op.create_table('venta_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venta_items_id'), 'venta_items', ['id'], unique=False)
    op.drop_index('ix_usuarios_email', table_name='usuarios')
    op.drop_index('ix_usuarios_id', table_name='usuarios')
    op.drop_index('ix_usuarios_username', table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('auditoria')
    op.drop_index('ix_clientes_email', table_name='clientes')
    op.create_index(op.f('ix_clientes_nombre'), 'clientes', ['nombre'], unique=False)
    op.drop_column('clientes', 'direccion')
    op.drop_constraint('proveedores_cuit_key', 'proveedores', type_='unique')
    op.drop_column('proveedores', 'direccion')
    op.drop_column('proveedores', 'activo')
    op.drop_column('proveedores', 'telefono')
    op.drop_column('proveedores', 'cuit')
    op.drop_column('proveedores', 'created_at')
    op.drop_constraint('uq_users_username', 'users', type_='unique')
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('ventas', 'fecha',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('ventas', 'total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index('ix_ventas_cliente_id', table_name='ventas')
    op.drop_constraint('ventas_cliente_id_fkey', 'ventas', type_='foreignkey')
    op.create_foreign_key(None, 'ventas', 'clientes', ['cliente_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ventas', type_='foreignkey')
    op.create_foreign_key('ventas_cliente_id_fkey', 'ventas', 'clientes', ['cliente_id'], ['id'])
    op.create_index('ix_ventas_cliente_id', 'ventas', ['cliente_id'], unique=False)
    op.alter_column('ventas', 'total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('ventas', 'fecha',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_unique_constraint('uq_users_username', 'users', ['username'])
    op.add_column('proveedores', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('proveedores', sa.Column('cuit', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('proveedores', sa.Column('telefono', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('proveedores', sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('proveedores', sa.Column('direccion', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('proveedores_cuit_key', 'proveedores', ['cuit'])
    op.add_column('clientes', sa.Column('direccion', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_clientes_nombre'), table_name='clientes')
    op.create_index('ix_clientes_email', 'clientes', ['email'], unique=True)
    op.create_table('auditoria',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('actor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('accion', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='auditoria_pkey')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='usuarios_pkey'),
    sa.UniqueConstraint('email', name='uq_usuarios_email'),
    sa.UniqueConstraint('username', name='uq_usuarios_username')
    )
    op.create_index('ix_usuarios_username', 'usuarios', ['username'], unique=True)
    op.create_index('ix_usuarios_id', 'usuarios', ['id'], unique=False)
    op.create_index('ix_usuarios_email', 'usuarios', ['email'], unique=True)
    op.drop_index(op.f('ix_venta_items_id'), table_name='venta_items')
    op.drop_table('venta_items')
    op.drop_index('ix_audit_tbl_rec_time', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index('ix_audit_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
