name: backend-ci

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FastAPI (background)
        env:
          # Forzamos uso de SQLite de archivo para CI
          DATABASE_URL: "sqlite:///./test_ci.db"
        run: |
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 > uvicorn.log 2>&1 &
          # Espera activa del health
          for i in {1..30}; do
            echo "Esperando /health (intento $i)..."
            curl -sf http://localhost:8000/health >/dev/null && break
            sleep 1
          done
          curl -s http://localhost:8000/health || (echo "Health no responde" && exit 1)

      - name: Run tests (httpx contra server real)
        env:
          API_BASE_URL: "http://localhost:8000"
          ADMIN_USERNAME: "admin"
          ADMIN_PASSWORD: "admin123"
        run: |
          pytest -q

      - name: Uvicorn logs (always show)
        if: always()
        run: |
          echo "=== Uvicorn logs ==="
          cat uvicorn.log || true
