name: backend-ci

on:
  push:
    paths:
      - "backend/**"
      - "infra/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build services
        run: docker compose -f infra/docker-compose.yml build

      - name: Start services
        run: docker compose -f infra/docker-compose.yml up -d db redis backend

      - name: Wait for backend /health
        run: |
          for i in {1..60}; do
            if curl -fsS http://localhost:8000/health; then
              echo "Backend is up"; exit 0
            fi
            echo "Waiting backend... ($i)"
            sleep 2
          done
          echo "Backend not healthy in time"
          docker compose -f infra/docker-compose.yml logs backend
          exit 1

      - name: Run tests
        run: docker compose -f infra/docker-compose.yml exec -T backend pytest -q

      - name: Show logs on failure
        if: failure()
        run: docker compose -f infra/docker-compose.yml logs

      - name: Tear down
        if: always()
        run: docker compose -f infra/docker-compose.yml down -v
